# Generated by Django 2.0.5 on 2018-12-09 12:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Border',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.IntegerField(unique=True)),
                ('email', models.EmailField(max_length=254)),
                ('photo', models.FileField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Daily_cost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchased_date', models.DateTimeField(auto_now_add=True)),
                ('purchased_updated_on', models.DateTimeField(auto_now=True)),
                ('purchased_amount', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Daily_meal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meal_date', models.DateField(null=True)),
                ('order_date', models.DateTimeField(auto_now_add=True)),
                ('order_updated_date', models.DateTimeField(auto_now_add=True)),
                ('breakfast', models.BooleanField(default=False)),
                ('lunch', models.BooleanField(default=False)),
                ('dinner', models.BooleanField(default=False)),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meal.Border')),
            ],
        ),
        migrations.CreateModel(
            name='Personal_deposit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deposit_date', models.DateTimeField(auto_now_add=True)),
                ('deposit_updated_on', models.DateTimeField(auto_now=True)),
                ('deposit_amount', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Shopping_date',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allotted_date', models.DateField(blank=True, null=True)),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meal.Border')),
            ],
        ),
        migrations.CreateModel(
            name='User_information',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('institute', models.CharField(max_length=100)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User Name')),
            ],
        ),
        migrations.AddField(
            model_name='daily_cost',
            name='purchased_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meal.User_information'),
        ),
        migrations.AddField(
            model_name='border',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='meal.User_information'),
        ),
    ]
