# Generated by Django 2.0.5 on 2018-12-09 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='border',
            name='phone_number',
            field=models.CharField(max_length=11, unique=True),
        ),
    ]
